apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CBP-14953-approval
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
metadata:
  stages/v1alpha1:
    - name: QA
      jobs:
        - deploy-to-QA
    - name: staging
      jobs:
        - deploy-to-staging
    - name: production
      jobs:
        - deploy-to-production
jobs:
  deploy-to-QA:
    steps:
      - name: Deploy to QA
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to QA"
  deploy-to-staging:
    needs:
      - deploy-to-QA
    steps:
      - name: Deploy to staging
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to staging"
  deploy-to-production:
    needs:
      - deploy-to-staging
    steps:
      - name: Deploy to production
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to production"
