apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy-on-demand-standard-wf
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  deploy:
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ inputs.environment }}
