apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
inputs:
  environment:
    type: string
    required: true
'on':
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
jobs:
  MyAppAPIs:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppAPIs
      artifactVersion: 2.0.5-0.0.17
      environment: ${{ inputs.environment }}
  MyAppFE:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppFE
      artifactVersion: 3.0.3-0.0.14
      environment: ${{ inputs.environment }}
  MyAppBE:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName: MyAppBE
      artifactVersion: 2.2.0-0.0.21
      environment: ${{ inputs.environment }}
