apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  MyAppAPIs:
    if: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].deploy }}
    uses: gmaxey/MyAppAPIs/.cloudbees/workflows/deploy.yaml
    with:
      artifactName: MyAppAPIs
      artifactVersion: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].version }}
      environment: ${{ inputs.environment }}
  MyAppFE:
    if: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].deploy }}
    uses: gmaxey/MyAppFE/.cloudbees/workflows/deploy.yaml
    with:
      artifactName: MyAppFE
      artifactVersion: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].version }}
      environment: ${{ inputs.environment }}
  MyAppBE:
    if: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].deploy }}
    uses: gmaxey/MyAppBE/.cloudbees/workflows/deploy.yaml
    with:
      artifactName: MyAppBE
      artifactVersion: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].version }}
      environment: ${{ inputs.environment }}
