apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: enum
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
      enum:
        type: choice
        options:
          - a
          - b
          - c
        default: ""
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
