apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: fail
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
jobs:
  build:
    steps:
      - name: NOP
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo NOP     
      - name: throw error
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          exit 9999
