apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-staged-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: Parameter required for release workflows
        
metadata:
  stages/v1alpha1:
    - name: env1
      jobs:
        - deploy-env1
    - name: env2
      jobs:
        - deploy-env2
    - name: env3
      jobs:
        - deploy-env2

jobs:
  deploy-env1:
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
  deploy-env2:
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
  deploy-env3:
    steps:
      - name: Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo Deploying...
