apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: QA
      jobs:
        - deploy-to-QA
    - name: pre-prod
      jobs:
        - deploy-to-pre-prod
    - name: prod
      jobs:
        - deploy-to-prod
jobs:
  deploy-to-QA:
    steps:
      - name: Deploy to QA
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to QA"
  deploy-to-pre-prod:
    needs:
      - deploy-to-QA
    steps:
      - name: Deploy to pre-prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to pre-prod"
  deploy-to-prod:
    needs:
      - deploy-to-pre-prod
    steps:
      - name: Deploy to prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to prod"
