apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Release with resuable workflows deployer
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
jobs:
  pre-prod:
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      environment: pre-prod
  prod:
    needs: pre-prod
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      environment: prod
