apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged Release with deployer
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true

metadata:
  stages/v1alpha1:
    - name: pre-prod
      jobs:
        - pre-prod
    - name: prod
      jobs:
        - prod
jobs:
  pre-prod:
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: myapp-pre-prod
  prod:
    needs: pre-prod
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: myapp-prod
