apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged Release with hard coded deploy steps
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
metadata:
  stages/v1alpha1:
    - name: pre-prod
      jobs:
        - MyAppAPIs-pre
        - MyAppFE-pre
        - MyAppBE-pre
    - name: prod
      jobs:
        - MyAppAPIs-prod
        - MyAppFE-prod
        - MyAppBE-prod
jobs:
  MyAppAPIs-pre:
    environment: pre-prod
    steps:
      - name: Deploy MyAppAPIs
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].digest }}
          target-environment: myapp-pre-prod
          action-name: MyAppAPIs
  MyAppFE-pre:
    needs:
      - MyAppAPIs-pre
    environment: pre-prod
    steps:
      - name: Deploy MyAppFE
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].digest }}
          target-environment: myapp-pre-prod
          action-name: MyAppFE
  MyAppBE-pre:
    needs:
      - MyAppFE-pre
    environment: pre-prod
    steps:
      - name: Deploy MyAppBE
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].digest }}
          target-environment: myapp-pre-prod
          action-name: MyAppBE
  MyAppAPIs-prod:
    needs:
      - MyAppBE-pre
    environment: prod
    steps:
      - name: Deploy MyAppAPIs
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppAPIs']['MyAppAPIs'].digest }}
          target-environment: myapp-prod
          action-name: MyAppAPIs
  MyAppFE-prod:
    needs:
      - MyAppAPIs-prod
    environment: prod
    steps:
      - name: Deploy MyAppFE
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppFE']['MyAppFE'].digest }}
          target-environment: myapp-prod
          action-name: MyAppFE
  MyAppBE-prod:
    needs:
      - MyAppFE-prod
    environment: prod
    steps:
      - name: Deploy MyAppBE
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].version }}
          url: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].url }}
          digest: ${{ fromJSON(inputs.manifest)['MyAppBE']['MyAppBE'].digest }}
          target-environment: myapp-prod
          action-name: MyAppBE
