apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Staged Release with deployer
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
metadata:
  stages/v1alpha1:
    - name: pre-prod
      jobs:
        - Gather-evidence
        - pre-prod
    - name: prod
      jobs:
        - Production-Approval
        - prod
jobs:
  pre-prod:
    needs: Gather-evidence
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: myapp-pre-prod
  Production-Approval:
    needs: pre-prod
    timeout-minutes: 4320
    with:
      instructions: Please approve for production deployment
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  prod:
    needs: Production-Approval
    uses: gmaxey/MyApp/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: myapp-prod
  Gather-evidence:
    steps:
      - name: Publish evidence
        with:
          content: "Tickets Closed: MYAPP-12237, MYAPP-12256, MYAPP-12261"
        uses: cloudbees-io/publish-evidence-item@v1
  
